### Aim of this notebook is to explore the dataset

##### Import modules

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

#### Import data

In [4]:
## Import csv file with semicolon delimiter
df = pd.read_csv('../data/Final_Africa_Master_File 2.csv', delimiter=';', decimal=',')
print('df shape:', df.shape)

pd.set_option('display.max_columns', None)
df.head(5)

df shape: (472894, 111)

,Year,ID,Countries,lat,lon,Sow_Maize,Harvest_Maize,Sow_Rice,Harvest_Rice,Sow_Wheat,Harvest_Wheat,Depth_1,Depth_2,Depth_3,Depth_4,Depth_5,Depth_6,Depth_7,BD_1,BD_2,BD_3,BD_4,BD_5,BD_6,BD_7,Sand_1,Sand_2,Sand_3,Sand_4,Sand_5,Sand_6,Sand_7,Clay_1,Clay_2,Clay_3,Clay_4,Clay_5,Clay_6,Clay_7,OC_1,OC_2,OC_3,OC_4,OC_5,OC_6,OC_7,PAW_1,PAW_2,PAW_3,PAW_4,PAW_5,PAW_6,PAW_7,pcp_1,pcp_2,pcp_3,pcp_4,pcp_5,pcp_6,pcp_7,pcp_8,pcp_9,pcp_10,pcp_11,pcp_12,tmax_1,tmax_2,tmax_3,tmax_4,tmax_5,tmax_6,tmax_7,tmax_8,tmax_9,tmax_10,tmax_11,tmax_12,tmin_1,tmin_2,tmin_3,tmin_4,tmin_5,tmin_6,tmin_7,tmin_8,tmin_9,tmin_10,tmin_11,tmin_12,spi_12mon_1,spi_12mon_2,spi_12mon_3,spi_12mon_4,spi_12mon_5,spi_12mon_6,spi_12mon_7,spi_12mon_8,spi_12mon_9,spi_12mon_10,spi_12mon_11,spi_12mon_12,Y_maize,Y_maize_major,Y_maize_second,Y_rice,Y_rice_major,Y_rice_second,Y_soybean,Y_wheat,Y_wheat_spring,Y_wheat_winter
0,1950,V6089,Abyei,9.75,28.25,NaN,NaN,NaN,NaN,NaN,NaN,0.1,0.1,0.2,0.3,0.6,1,2,1.49,1.46,1.46,1.47,1.53,1.57,1.57,44,45,44,42,41,41,45,36,35,37,38,41,40,38,0.44,0.35,0.33,0.28,0.27,0.26,0.26,0.11,0.11,0.11,0.11,0.10,0.09,0.09,0.000000,0.000000,41.655540,75.657129,127.582073,199.727531,21.462202,171.083927,282.638073,363.204001,166.133404,20.305157,308.120532,308.842431,308.203092,309.593115,305.409658,301.922915,304.241880,303.184332,301.320442,300.763411,301.072137,303.114412,293.449902,294.449762,296.348937,297.920061,296.728350,295.369351,295.710211,295.856574,294.451473,293.486874,293.037954,293.409049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.125672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1950,V6090,Abyei,9.75,28.75,NaN,NaN,NaN,NaN,NaN,NaN,0.1,0.1,0.2,0.3,0.6,1,2,1.48,1.45,1.45,1.47,1.51,1.53,1.54,47,49,47,44,42,43,44,35,34,36,39,41,42,40,0.44,0.35,0.33,0.28,0.26,0.26,0.26,0.12,0.11,0.11,0.11,0.10,0.09,0.10,0.000000,0.002384,45.643330,91.853380,156.178474,225.781202,22.833824,174.277306,276.149988,348.754644,190.218926,28.559685,308.283424,309.058202,308.264435,309.127257,304.532952,301.702727,303.581545,302.752955,301.457568,300.842988,301.092897,302.726084,293.522231,294.686266,296.475251,297.701274,296.352086,295.235677,295.095103,295.513684,294.386661,293.627069,293.218281,293.361476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.291257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1950,V5958,Algeria,35.25,-0.25,15-Feb,30-Aug,NaN,NaN,15-Oct,15-Jul,0.1,0.1,0.2,0.3,0.6,1,2,1.54,1.46,1.51,1.54,1.64,1.67,1.67,44,44,44,42,42,42,44,26,25,26,30,31,30,29,0.29,0.13,0.11,0.06,0.04,0.03,0.03,0.12,0.12,0.11,0.10,0.08,0.07,0.07,96.568346,39.580822,56.350231,41.012526,27.049780,0.692129,2.216816,8.283138,42.657852,44.573784,7.163525,180.089951,286.096166,289.236481,290.449158,292.874119,297.995312,303.643564,309.028932,308.040693,303.213057,296.291210,293.708325,286.008002,277.524521,278.288162,278.460426,280.983176,284.626571,289.214257,292.483529,293.237505,290.079923,286.295030,282.349635,278.456066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.996847,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1950,V5957,Algeria,34.75,-0.25,15-Feb,30-Aug,NaN,NaN,15-Oct,15-Jul,0.1,0.1,0.2,0.3,0.6,1,2,1.55,1.50,1.54,1.59,1.63,1.65,1.65,42,42,41,40,40,42,44,26,26,28,29,31,29,28,0.29,0.11,0.10,0.05,0.04,0.03,0.03,0.12,0.12,0.11,0.09,0.08,0.07,0.07,92.652082,27.337790,39.147854,29.808998,39.578199,3.199577,1.346111,20.002365,54.835320,61.732292,7.457256,143.360853,283.093715,286.960458,287.986720,291.315377,297.711248,304.722547,308.825254,306.996307,301.406503,293.526974,291.675899,283.065016,274.363522,274.949650,275.082974,277.695259,281.755466,287.234003,290.843920,290.684198,286.963944,282.823782,278.865118,274.971573,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.773148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1950,V5938,Algeria,23.75,-1.25,15-Feb,30-Aug,NaN,NaN,15-Oct,15-Jul,0.1,0.1,0.2,0.3,0.6,1,2,1.54,1.48,1.50,1.53,1.51,1.56,1.57,94,94,94,94,94,96,92,4,3,3,2,3,2,6,0.01,0.04,0.05,0.02,0.01,0.01,0.01,0.05,0.04,0.04,0.05,0.05,0.05,0.05,8.211136,0.000000,0.000000,0.000477,0.097752,0.000000,0.000477,7.845402,2.161980,0.055313,0.000000,0.000000,291.624614,296.231087,300.816778,306.172037,309.694186,316.603857,315.981715,314.336709,312.871503,306.014487,300.424367,293.790016,278.740957,282.052158,284.940049,290.558410,294.142412,299.496195,301.170411,301.164153,298.701195,292.634889,285.678934,279.179435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.823487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
### Idenfity unique values in column df['Depth_1']
df['Sow_Maize'].unique()

array([nan, '15-Feb', '01-Sep', '01-Mar', '01-Jan', '01-Apr', '01-Jun',
       '01-Jul', '15-Apr', '01-May', '15-Mar', '01-Nov', '15-Sep',
       '01-Oct', '01-Dec', '15-Oct'], dtype=object)

In [6]:
### Remove constant colummns
df = df.drop(['Depth_1', 'Depth_2', 'Depth_3', 'Depth_4', 'Depth_5', 'Depth_6', 'Depth_7'], axis=1)

### Fill NAs and automatically recognize columns

In [7]:
## Replace all NAs with 0
df = df.fillna(0)

# Infer data types (try to detect numeric types)
df = df.infer_objects()

### Describe numeric columns

In [8]:
## Display all columns
pd.set_option('display.max_columns', None)
## Explore numeric columns of df
df.describe()

,Year,lat,lon,BD_1,BD_2,BD_3,BD_4,BD_5,BD_6,BD_7,Sand_1,Sand_2,Sand_3,Sand_4,Sand_5,Sand_6,Sand_7,Clay_1,Clay_2,Clay_3,Clay_4,Clay_5,Clay_6,Clay_7,OC_1,OC_2,OC_3,OC_4,OC_5,OC_6,OC_7,PAW_1,PAW_2,PAW_3,PAW_4,PAW_5,PAW_6,PAW_7,pcp_1,pcp_2,pcp_3,pcp_4,pcp_5,pcp_6,pcp_7,pcp_8,pcp_9,pcp_10,pcp_11,pcp_12,tmax_1,tmax_2,tmax_3,tmax_4,tmax_5,tmax_6,tmax_7,tmax_8,tmax_9,tmax_10,tmax_11,tmax_12,tmin_1,tmin_2,tmin_3,tmin_4,tmin_5,tmin_6,tmin_7,tmin_8,tmin_9,tmin_10,tmin_11,tmin_12,spi_12mon_1,spi_12mon_2,spi_12mon_3,spi_12mon_4,spi_12mon_5,spi_12mon_6,spi_12mon_7,spi_12mon_8,spi_12mon_9,spi_12mon_10,spi_12mon_11,spi_12mon_12,Y_maize,Y_maize_major,Y_maize_second,Y_rice,Y_rice_major,Y_rice_second,Y_soybean,Y_wheat,Y_wheat_spring,Y_wheat_winter
count,472894.00000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000,472894.000000
mean,1986.00000,-0.389781,21.865159,1.393478,1.356414,1.386629,1.411547,1.426723,1.443199,1.448557,56.514974,58.175208,57.047082,54.650046,52.675826,52.790985,53.039210,26.557734,24.688793,26.243748,28.786045,31.254708,31.306422,31.050942,0.326800,0.175622,0.143776,0.090546,0.064112,0.051740,0.050570,0.122484,0.123892,0.118591,0.110069,0.097265,0.086056,0.083870,91.672295,84.276770,96.008996,85.529430,67.935613,56.769335,70.566785,85.346853,86.345508,93.561837,88.472034,90.268671,301.638317,302.477621,302.950163,302.767894,302.357845,301.539830,301.024154,301.564498,302.510319,302.609644,297.883797,297.330952,290.580870,291.237626,291.979813,292.098355,291.591594,290.669940,290.312702,290.795218,291.544663,291.804787,287.255942,286.646895,-0.010301,-0.009962,-0.009384,-0.009256,-0.009164,-0.008684,-0.007786,-0.008146,-0.008619,-0.008042,-0.007137,-0.010254,0.431116,0.383747,0.128683,0.174808,0.181691,0.012488,0.062083,0.391517,0.336553,0.118366
std,21.07133,16.161858,15.295821,0.132886,0.139621,0.123480,0.121446,0.115863,0.119169,0.120042,14.024252,14.159987,14.204519,14.013855,14.119511,14.167054,13.732181,9.034231,9.012767,9.227806,9.433119,9.895417,10.128292,9.645511,0.204758,0.127871,0.095528,0.076303,0.069898,0.066091,0.067565,0.028454,0.031178,0.026579,0.025647,0.027822,0.032061,0.032909,117.471361,102.843809,101.984973,91.767490,89.852021,88.728664,109.066580,123.586417,112.015976,104.762191,99.539929,110.796132,5.345367,5.329760,5.169368,5.210383,5.276884,5.731999,5.494540,4.703220,3.873296,3.787120,35.365678,35.390380,5.098220,4.931977,4.672778,4.862903,5.519086,6.289838,6.289669,5.573518,4.521260,3.988149,34.108076,34.115637,1.078599,1.075819,1.070249,1.069048,1.067295,1.064649,1.058846,1.060901,1.063060,1.059761,1.045773,1.075652,0.900315,0.880319,0.445306,0.761084,0.776284,0.149214,0.480082,1.996663,2.030462,0.810668
min,1950.00000,-34.750000,-17.250000,0.780000,0.760000,0.790000,0.830000,0.920000,0.810000,0.810000,12.000000,13.000000,13.000000,11.000000,12.000000,11.000000,11.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000,2.000000,0.010000,0.020000,0.030000,0.010000,0.010000,0.010000,0.010000,0.020000,0.020000,0.020000,0.030000,0.020000,0.010000,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,274.071692,274.612998,276.109469,279.509650,280.614219,276.011533,274.121428,278.747465,283.284071,284.112123,0.000000,0.000000,262.630853,262.544192,266.366983,269.089376,267.868664,264.134439,262.537302,266.061494,269.895578,272.845759,0.000000,0.000000,-14.834211,-14.862780,-18.594524,-18.679498,-18.391938,-19.797722,-20.253385,-20.178804,-20.545911,-19.439519,-12.175019,-12.277812,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1968.00000,-12.750000,14.250000,1.290000,1.250000,1.290000,1.320000,1.340000,1.360000,1.360000,47.000000,48.000000,47.000000,45.000000,43.000000,43.000000,43.000000,21.000000,19.000000,21.000000,24.000000,26.000000,26.000000,26.000000,0.180000,0.080000,0.080000,0.050000,0.030000,0.020000,0.020000,0.110000,0.100000,0.100000,0.090000,0.080000,0.060000,0.060000,0.749588,1.184464,7.628918,12.233257,3.590584,0.803947,0.549793,1.196384,3.632069,11.923611,6.890595,1.170635,299.342402,299.678396,299.812675,299.551382,299.074302,298.140789,297.953982,299.370909,300.662024,300.639074,299.847496,299.229866,289.053447,289.563216,289.748750,288.926479,287.701100,286.471491,286.113480,287.267389,288.921776,289.663266,289.122012,288.830589,-0.595918,-0.596205,-0.600934,-0.598902,-0.594645,-0.595983,-0.598927,-0.600396,-0.605972,-0.603104,-0.594039,-0.589345,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1986.00000,1.750000,23.750000,1.400000,1.370000,1.400000,1.420000,1.430000,1.440000,1.450000,56.000000,58.000000,56.000000,53.500000,51.000000,51.000000,51.000000,27.000000,25.000000,27.000000,30.000000,33.000000,33.000000,32.000000,0.310000,0.140000,0.120000,0.070000,0.050000,0.030000,0.030000,0.120000,0.120000,0.120000,0.110000,0.100000,0.090000,0.090000,36.224484,41.384935,65.419316,57.254553,29.280663,11.224866,10.291100,16.809463,29.609203,51.882148,53.337097,41.157961,302.377513,302.784863,302.689755,302.244819,302.074716,301.597086,301.117460,301.500734,302.412384,302.595850,302.196738,302.104055,291.729523,292.277936,292.889427,292.948697,292.718081,292.268704,292.257008,292.530929,292.652651,292.783482,292.241280,291.665508,0.031998,0.027432,0.026320,0.033024,0.030410,0.026217,0.023989,0.025183,0.026133,0.022613,0.000000,0.025475,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2004.00000,9.750000,32.750000,1.500000,1.470000,1.480000,1.500000,1.510000,1.530000,1.530000,66.000000,68.000000,67.000000,63.000000,61.000000,61.000000,61.000000,32.000000,30.000000,32.000000,35.000000,37.000000,38.000000,37.000000,0.460000,0.240000,0.180000,0.110000,0.070000,0.060000,0.060000,0.140000,0.140000,0.140000,0.130000,0.120000,0.110000,0.110000,159.018755,144.106567,162.015915,138.872504,110.004127,90.375185,121.380627,153.334975,153.633356,155.605495,147.148848,159.024894,305.399146,306.393090,306.495625,305.686163,305.294658,304.818618,304.043510,303.833220,304.557513,304.968588,304.919248,304.904351,293.990839,294.578771,295.335644,295.821455,295.849860,295.421400,294.894405,294.742127,294.741409,294.654719,294.190693,293.848748,0.647076,0.645415,0.652388,0.652798,0.652048,0.652845,0.651073,0.652849,0.655672,0.650494,0.630824,0.643535,0.608693,0.349789,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,2022.00000,37.250000,57.750000,1.760000,1.720000,1.710000,1.730000,1.760000,1.810000,1.810000,97.000000,97.000000,97.000000,96.000000,97.000000,98.000000,96.000000,60.000000,60.000000,61.000000,61.000000,62.000000,62.000000,61.000000,1.520000,1.630000,1.520000,1.490000,1.520000,1.490000,1.550000,0.340000,0.350000,0.330000,0.290000,0.240000,0.310000,0.300000,2878.879803,1638.737438,2591.996410,2106.691833,2096.317287,1864.405148,2404.998541,2647.420643,2109.203579,1930.661690,1891.200073,2732.566391,313.169163,314.163940,316.406570,316.535534,317.070935,319.311765,320.201306,318.902572,317.127529,314.044629,313.115789,312.245498,301.042677,302.494404,303.088114,302.924452,304.048893,304.491567,305.448737,305.634850,304.831750,303.978022,301.107313,300.654403,4.670594,4.550807,4.455978,4.737657,5.120531,5.176842,5.030835,4.886923,5.189893,5.538786,5.334731,5.432645,14.542289,14.542289,7.566601,19.452080,19.452080,5.187599,13.383948,19.298248,19.298248,15.636001

### Categorical fields

In [9]:
## Create new df with columns that of df that are not numeric
df_cat = df.select_dtypes(exclude=['int64', 'float64'])
print('df_cat shape:', df_cat.shape)
df_cat.head(5)

df_cat shape: (472894, 8)

,ID,Countries,Sow_Maize,Harvest_Maize,Sow_Rice,Harvest_Rice,Sow_Wheat,Harvest_Wheat
0,V6089,Abyei,0,0,0,0,0,0
1,V6090,Abyei,0,0,0,0,0,0
2,V5958,Algeria,15-Feb,30-Aug,0,0,15-Oct,15-Jul
3,V5957,Algeria,15-Feb,30-Aug,0,0,15-Oct,15-Jul
4,V5938,Algeria,15-Feb,30-Aug,0,0,15-Oct,15-Jul

In [10]:
cat_cols = df_cat.columns[1:]
cat_cols

Index(['Countries', 'Sow_Maize', 'Harvest_Maize', 'Sow_Rice', 'Harvest_Rice',
       'Sow_Wheat', 'Harvest_Wheat'],
      dtype='object')

In [11]:
df_cat['Sow_Maize'].unique()

array([0, '15-Feb', '01-Sep', '01-Mar', '01-Jan', '01-Apr', '01-Jun',
       '01-Jul', '15-Apr', '01-May', '15-Mar', '01-Nov', '15-Sep',
       '01-Oct', '01-Dec', '15-Oct'], dtype=object)

##### Label encoding

In [12]:

## Convert all cat_cols to to string and apply encoder
le = LabelEncoder()
for column in cat_cols:
    df[column] = df[column].astype('str')
    df[column] = le.fit_transform(df[column])

    
df[cat_cols].head(5)

,Countries,Sow_Maize,Harvest_Maize,Sow_Rice,Harvest_Rice,Sow_Wheat,Harvest_Wheat
0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0
2,1,12,7,0,0,7,1
3,1,12,7,0,0,7,1
4,1,12,7,0,0,7,1

### Calculate lagged variables
- Yield from previous years
- As we are forecasting only one year ahead, we can save previous years into variables and use in any model

In [13]:
# Number of lags
num_lags = 5

# Create lagged variables
for i in range(1, num_lags + 1):
    df[f'Y_rice_lag_{i}'] = df['Y_rice'].shift(i)
    df[f'Y_maize_lag_{i}'] = df['Y_maize'].shift(i)
    df[f'Y_wheat_lag_{i}'] = df['Y_wheat'].shift(i)
    df[f'Y_soybean_lag_{i}'] = df['Y_soybean'].shift(i)


df.filter(like='lag').head(5)

,Y_rice_lag_1,Y_maize_lag_1,Y_wheat_lag_1,Y_soybean_lag_1,Y_rice_lag_2,Y_maize_lag_2,Y_wheat_lag_2,Y_soybean_lag_2,Y_rice_lag_3,Y_maize_lag_3,Y_wheat_lag_3,Y_soybean_lag_3,Y_rice_lag_4,Y_maize_lag_4,Y_wheat_lag_4,Y_soybean_lag_4,Y_rice_lag_5,Y_maize_lag_5,Y_wheat_lag_5,Y_soybean_lag_5
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN

### Create and X and y dataframes

In [14]:
# Filter based on the minimum year (for the first years, we dont have values for the lags)
min_year = 1950 + num_lags
df_filtered = df[df['Year'] >= min_year].reset_index(drop=True)

In [15]:
## Create featues dataset by dropping all columns starting with 'Y_' without lag, but including all lag columns
X = df_filtered.drop(df_filtered.filter(like='Y_').columns.difference(df.filter(like='lag').columns), axis=1)
pd.set_option('display.max_columns', None)


## Drop ID column 
X = X.drop(['ID'], axis=1)
print(X.shape)
X.head(5)

X = X.fillna(0)

(440504, 113)

In [16]:
y = df_filtered['Y_maize']
y = y.fillna(0)

In [17]:
Label = df_filtered['ID']

### Split X and y into train and test sets

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print('X_train shape:', X_train.shape)
print('y_train shape:', y_train.shape)

print('\nX_test shape:', X_test.shape)
print('y_test shape:', y_test.shape)

X_train shape: (352403, 113)
y_train shape: (352403,)

X_test shape: (88101, 113)
y_test shape: (88101,)

### Train and evaluate baseline models

In [33]:
from sklearn.model_selection import cross_val_score, KFold
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import make_scorer, mean_absolute_error

#### Limit number of rows (to increase speed)

In [44]:
n_rows =  100

In [49]:
# Create a Random Forest classifier
rf = RandomForestRegressor(n_estimators=100, random_state=42)

# Specify the number of folds for cross-validation
n_folds = 5

# Create a KFold object
kf = KFold(n_splits=n_folds, shuffle=False)

# Specify mean absolute error as metric
cv_scores = cross_val_score(rf, X_train.head(n_rows), y_train.head(n_rows), cv=kf, scoring='neg_mean_absolute_error')

cv_scores = cv_scores*-1


# Perform cross-validation
#cv_scores = cross_val_score(rf , X_train.head(n_rows), y_train.head(n_rows), cv=kf)


# Print the mean and standard deviation of the cross-validation scores
print(f"Mean CV Score: {cv_scores.mean():.4f}")
print(f"Std CV Score: {cv_scores.std():.4f}")

Mean CV Score: 0.3138
Std CV Score: 0.0769